# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "public/"
  command = "gatsby build"
  functions = "functions/"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/mailer"
  to = "/.netlify/functions/mailer"
  status = 200

  [redirects.headers]
     Access-Control-Allow-Origin = "*"
