# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "public/"
  command = "gatsby build"
  functions = "functions/"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
